[TOKEN]
code = "W3C"
issuer = "GCIPTMBGZ2IXATBZPZTLQYT7OLUC7IJTDBKTFIUAFM4A35R6UU5BLN3W"
name = "Web3Currency"
desc = "Official token for the Web3 currency project on Pi Network, used for governance, rewards, access to exclusive content, and powering decentralized Web3 initiatives within the Pi ecosystem."
website = "https://web3currency.github.io/W3C-Token"
email = "web3currency.info@gmail.com"
twitter = "https://x.com/web3currencyNG"
logo = "https://i.postimg.cc/jDjX4qYG/W3C.png"
fixed_number = 6
max_supply = 628000
is_revocable = false
